import { getStore } from "@netlify/blobs";
import { randomUUID, randomBytes } from "node:crypto";
import { httpError } from "./respond.js";

/** Single blob holding every entry's metadata — one read serves /api/entries */
const INDEX_KEY = "index";

/** Image keys are generated by newImageKey(); nothing else is readable */
const IMAGE_KEY_RE = /^[a-z0-9]{8,16}-[a-f0-9]{16}\.(jpg|png|webp|gif)$/;

/** Cache tag on /api/entries, purged after every write */
export const ENTRIES_CACHE_TAG = "music-entries";

/** Local dev (scripts/dev.js) points the stores at a local Blobs server */
let clientOptions = {};
export function configureStores(options) {
  clientOptions = options || {};
}

export function imagesStore() {
  return getStore({ name: "music-images", ...clientOptions });
}

function dataStore() {
  return getStore({ name: "music-data", ...clientOptions });
}

export function isImageKey(key) {
  return typeof key === "string" && IMAGE_KEY_RE.test(key);
}

export function newImageKey(ext) {
  return `${Date.now().toString(36)}-${randomBytes(8).toString("hex")}.${ext}`;
}

export function newEntryId() {
  return randomUUID();
}

function normalizeIndex(raw) {
  return { entries: raw && Array.isArray(raw.entries) ? raw.entries : [] };
}

async function readIndexWithEtag() {
  const res = await dataStore().getWithMetadata(INDEX_KEY, { type: "json" });
  if (!res) return { index: normalizeIndex(null), etag: null };
  return { index: normalizeIndex(res.data), etag: res.etag };
}

export async function readIndex() {
  const { index } = await readIndexWithEtag();
  return index;
}

/**
 * Read-modify-write the index under an ETag compare-and-swap so two concurrent
 * edits can't clobber each other. `mutator` may run more than once, so it must
 * only touch the index — do side effects (like storing an image) beforehand.
 * Returns { result, index } so callers can answer with the fresh timeline.
 */
export async function mutateIndex(mutator, attempts = 5) {
  const store = dataStore();

  for (let i = 0; i < attempts; i++) {
    const { index, etag } = await readIndexWithEtag();
    const result = await mutator(index);

    const { modified } = await store.setJSON(
      INDEX_KEY,
      index,
      etag ? { onlyIfMatch: etag } : { onlyIfNew: true }
    );

    if (modified) return { result, index };
  }

  throw httpError(409, "Timeline was busy — please try again");
}

/** Public shape of an entry — only fields the page needs */
export function serializeEntry(entry) {
  return {
    id: entry.id,
    year: entry.year,
    end_year: entry.end_year ?? null,
    circa: !!entry.circa,
    title: entry.title,
    description: entry.description || "",
    links: Array.isArray(entry.links) ? entry.links : [],
    image_url: entry.image_key ? `/api/media?id=${encodeURIComponent(entry.image_key)}` : null,
    image_alt: entry.image_alt || ""
  };
}

export function byDate(a, b) {
  return (
    a.year - b.year ||
    (a.end_year ?? a.year) - (b.end_year ?? b.year) ||
    String(a.created_at).localeCompare(String(b.created_at))
  );
}

export function serializeTimeline(index) {
  return { entries: [...index.entries].sort(byDate).map(serializeEntry) };
}
